apiVersion: apps/v1
kind: Deployment
metadata:
  name: "node-server"
  labels:
    app: "node-server"
spec:
  selector:
    matchLabels:
      app: "node-server"
  replicas: 3
  template:
    metadata:
      name: "node-server"
      labels:
        app: "node-server"
    spec:
      containers:
        - name: "node-server"
          image: "agostinhoneto/hello-node:v5"
