apiVersion: v1
kind: Service
metadata:
  name: "node-server-service"
spec:
  selector:
    app: "node-server"
  type: ClusterIP
  ports:
    - name: "node-server-service"
      port: 3000
      protocol: TCP
